USE ContosoRetailDW

SELECT GETDATE() AS DATA_ATUAL

SELECT GETDATE()+10 AS DATA_ATUAL_10

SELECT YEAR(GETDATE()) AS ANO
SELECT MONTH(GETDATE()) AS MES
SELECT DAY(GETDATE()) AS DIA


SELECT
	*
FROM FactOnlineSales
WHERE YEAR(DateKey) = 2007 AND
MONTH(DateKey) = 12 AND
DAY(DateKey) = 31