USE ContosoRetailDW

-- END OF MONTH
SELECT 
	EOMONTH(GETDATE())


-- ADICIONANDO 01 MÊS
SELECT
	GETDATE() AS DATA_ATUAL,
	EOMONTH(GETDATE()) AS MES_ATUAL, -- END OF MONTH
	EOMONTH(GETDATE(), 1) AS PROXIMO_MES, -- ADICIONA UM MÊS
	EOMONTH(GETDATE(), -1) AS MES_ANTERIOR -- SUBTRAI UM MÊS