USE ContosoRetailDW

-- DATEDIFF (intervalo, data_inicio, data_final)

SELECT 
	DATEDIFF(DAY, '2024-05-10', GETDATE()) AS DIA,
	DATEDIFF(MONTH, '2024-05-10', GETDATE()) AS MES,
	DATEDIFF(YEAR, '2002-05-10', GETDATE()) AS ANO

SELECT TOP 100
	S.DateKey,
	GETDATE() AS DATA_HOJE,
	DATEDIFF(DAY, S.DateKey, GETDATE()) AS DIFERENCA_DIAS
FROM FactOnlineSales AS S
ORDER BY 1 DESC