USE PRIMEIRO_BD

UPDATE CLIENTES
SET EMAIL = 'CESAR@GMAIL.COM.BR'
WHERE ID_CLIENTE = 1

UPDATE CLIENTES
SET 
	NOME = 'CESAR SANTOS 2', 
	EMAIL = 'CESARSANTOS@GMAIL.COM'
WHERE ID_CLIENTE = 1

SELECT * FROM CLIENTES